=== gravitee-io/gravitee-policy-rest-to-soap/src/main/resources/schemas/schema-form.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "envelope": {
            "title": "SOAP Envelope",
            "description": "SOAP envelope used to invoke WS. (support EL)",
            "type": "string",
            "x-schema-form": {
                "type": "codemirror",
                "codemirrorOptions": {
                    "placeholder": "Place your SOAP envelope here.",
                    "lineWrapping": true,
                    "lineNumbers": true,
                    "allowDropFileTypes": true,
                    "autoCloseTags": true,
                    "mode": "xml"
                },
                "expression-language": true
            },
            "format": "gio-code-editor",
            "gioConfig": {
                "monacoEditorConfig": {
                    "language": "xml"
                }
            },
            "examples": [
                "<?xml version=\"1.0\"?>\n<soap:Envelope xmlns:soap=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:web=\"http://www.oorsprong.org/websamples.countryinfo\"><soap:Header/><soap:Body><web:ListOfCountryNamesByName/></soap:Body></soap:Envelope>"
            ]
        },
        "soapAction": {
            "title": "SOAP Action",
            "description": "'SOAPAction' HTTP header send when invoking WS.",
            "type": "string"
        },
        "charset": {
            "title": "Charset",
            "description": "This charset will be appended to the Content-Type header value.",
            "type": "string"
        },
        "preserveQueryParams": {
            "title": "Preserve Query Parameters",
            "description": "Define if the query parameters are propagated to the backend SOAP service.",
            "type": "boolean",
            "default": false
        },
        "stripPath": {
            "title": "Strip path",
            "description": "Strip the path before propagating it to the backend SOAP service.",
            "type": "boolean",
            "default": false
        }
    },
    "required": ["envelope"]
}

=== gravitee-io/gravitee-policy-rest-to-soap/.docgen/examples/simple.json
{
    "envelope": "<?xml version=\"1.0\"?>\n<soap:Envelope xmlns:soap=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:web=\"http://www.oorsprong.org/websamples.countryinfo\"><soap:Header/><soap:Body><web:ListOfCountryNamesByName/></soap:Body></soap:Envelope>",
    "soapAction": "urn:MyAction",
    "charset": "UTF-8",
    "preserveQueryParams": true,
    "stripPath": false
}
